-- AlterTable
ALTER TABLE `order_items` ADD COLUMN `quantity_packed` DECIMAL(14, 3) NOT NULL DEFAULT 0,
    ADD COLUMN `quantity_picked` DECIMAL(14, 3) NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `order_status_history` MODIFY `from_status` ENUM('DRAFT', 'SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'STOCK_RESERVED', 'REJECTED', 'CANCELLED', 'PICKING', 'PACKED', 'READY_FOR_DISPATCH', 'DISPATCHED', 'PARTIALLY_FULFILLED', 'DELIVERED', 'COMPLETED') NULL,
    MODIFY `to_status` ENUM('DRAFT', 'SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'STOCK_RESERVED', 'REJECTED', 'CANCELLED', 'PICKING', 'PACKED', 'READY_FOR_DISPATCH', 'DISPATCHED', 'PARTIALLY_FULFILLED', 'DELIVERED', 'COMPLETED') NOT NULL;

-- AlterTable
ALTER TABLE `orders` MODIFY `status` ENUM('DRAFT', 'SUBMITTED', 'PENDING_APPROVAL', 'APPROVED', 'STOCK_RESERVED', 'REJECTED', 'CANCELLED', 'PICKING', 'PACKED', 'READY_FOR_DISPATCH', 'DISPATCHED', 'PARTIALLY_FULFILLED', 'DELIVERED', 'COMPLETED') NOT NULL DEFAULT 'DRAFT';
